apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe
  labels:
    app: probe
spec:
  selector:
    matchLabels:
      app: probe
  template:
    metadata:
      labels:
        app: probe
    spec:
      containers:
        - name: probe
          image: bryandollery/probe:1.3.0
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: robot-git-token
                  key: token
          volumeMounts:
            - name: ssh-key
              mountPath: /root/.ssh/
              readOnly: true
      volumes:
        - name: ssh-key
          secret:
            secretName: git-ssh-keys
            defaultMode: 0400
            items:
              - key: ssh-publickey
                path: id_rsa.pub
              - key: ssh-privatekey
                path: id_rsa
